# Generated by Django 2.2.16 on 2020-12-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='parent',
            field=models.CharField(default='defoult', max_length=30),
            preserve_default=False,
        ),
    ]
