# Generated by Django 2.2.16 on 2020-12-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_positions_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='media/', verbose_name='Ссылка картинки'),
        ),
    ]
